### ISSUE TITLE
`checkParamsEquality` throws an error

### ISSUE THREAD

**Issue by alexilyaev** [500tech/bdsm#100]
`TypeError: requestParams[key].match is not a function` in `bdsm/lib/api/interceptor.js`

The code:

```js
  checkParamsEquality(requestBody, responseParams) {
    const requestParams = UrlUtils.parseRequestBody(requestBody);
    const parameters    = Object.keys(requestParams);

    for (let key of parameters) {
      const regex = responseParams[key] ? new RegExp(responseParams[key]) : null;

      if (regex && !requestParams[key].match(regex)) {
        return false;
      }
    }

    return true;
  }
```

`requestBody`:
`"{"AccountID":21431,"StartTime":"2015-11-01T00:00:00"}"`

`responseParams`:
`{ AccountID: 21431 }`

I fails because `requestParams[key]` is a number value and not a string.

@morsdyce @ilyagelman 
I had a really hard time understanding what this function does, and it's still a puzzle why do we need the `RegExp`.
Why not save the request body on the mock and compare them as is?
If it's not an option, am I to assume this function should compare 2 objects?
Perhaps it's a good time to add Lodash.

**Comment by morsdyce** [comment]
We are doing this because we want to compare parameters with regex in the future so we could have a wildcard for a parameter if we don't care what is being sent and we want the same response.
