### ISSUE TITLE
Share mocks between ports

### ISSUE THREAD

**Issue by shmool** [500tech/bdsm#104]
When I run my app in a new port (i.e. 8081 instead of 8080) the mocks are not available. Thanks :)

**Comment by alexilyaev** [comment]
I think `localStorage` is bound to [Same Origin Policy](https://en.wikipedia.org/wiki/Same-origin_policy#Origin_determination_rules) and a different port is considered a different origin.

What is you specific use case?

**Comment by morsdyce** [comment]
Closing this as now you can set an app scope and use mocks synced from your project files.
