### ISSUE TITLE
Allow editing mocked URL and specifying regex

### ISSUE THREAD

**Issue by adamkleingit** [500tech/bdsm#121]
Working on it already...

**Comment by morsdyce** [comment]
What do you mean by specifying regex? What is the use case?

**Comment by adamkleingit** [comment]
you can write:
PUT /api/posts/*

And it will catch all following requests:
PUT /api/posts/1
PUT /api/posts/2
PUT /api/posts/3
etc...

...
ᐧ

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/> - Web and Mobile development
- hackademy.co.il <http://hackademy.co.il/angularjs/about> - AngularJS,
Ruby on Rails training
- (+972) 52 747 5633

**Comment by morsdyce** [comment]
Implemented ability to use wildcards in URL, still no full regex support.
