### ISSUE TITLE
Clash with cVIM plugin

### ISSUE THREAD

**Issue by gzohari** [500tech/bdsm#130]
On chrome, if "cVIM" extension is activated then requests are not captured.

**Comment by morsdyce** [comment]
Hi,
Which version are you using? I just tested out both XHR and fetch requests with the extension installed and had no issues.

Is it possible that this is caused by another plugin installed on your chrome? possibly ones that override the window XHR?

**Comment by gzohari** [comment]
Using version: "bdsmjs": "0.1.4",

It's cVim for sure. With cVim enabled, the "All captured requests" screen is empty, but with cVim enabled i'm getting some captured requests there.

**Comment by morsdyce** [comment]
This is a very old version, we're currently on version 0.3.1 in which I completely rewrote the UI and introduced many bug fixes to capturing requests.

Unfortunately this change introduced breaking changes in the data format so it is not backwards compatible.

If you don't mind recreating your mocks you can upgrade to the new version and enjoy a much better experience which should work with cVim enabled as well.

Thanks!
