### ISSUE TITLE
Pretty print JSON

### ISSUE THREAD

**Issue by gzohari** [500tech/bdsm#135]
Hi,

It'd be nice to have the JSON pretty printed when pasted in the "response body" section, or/and highlight JSON curly bracket start and end.

**Comment by morsdyce** [comment]
It's on the todo list, there are some technical difficulties regarding this feature from code mirror side.

**Comment by morsdyce** [comment]
Done!
Ref: 514dff7b196147a08e50e8cef36071937f3f837b, b1832313ea667f89d7a6f00409698fe1e54885d8

Released in v0.3.3
