### ISSUE TITLE
Question: how can I use BDSM in development without adding code in production

### ISSUE THREAD

**Issue by galtalmor** [500tech/bdsm#137]
I really like using the library while developing (awesome work!), but since I have to add the "import" line in my code, and I don't want it in production, it meant I have to remember to remove it before committing, or add a git ignore somewhere.
Did you guys think of a solution of some sort for this?
Thanks.

**Comment by morsdyce** [comment]
Hi Gal,

If you're using webpack you can use your environment variables to check in what environment you are currently running in using the webpack define plugin.

The config looks something like this:
```
plugins: [
   new webpack.DefinePlugin({
      __ENV: JSON.stringify(process.env.NODE_ENV || 'development')
    })
]
```

this way when you run your application, you can have code that checks if it should include BDSM or not.

For example:
```
if (__ENV === 'development') {
  require('bdsmjs');
}
```

to set different environments in osx/linux just add NODE_ENV=development before running your commands to start/build the application. (you can also do this in package.json)

**Comment by galtalmor** [comment]
I didn't manage to do what you suggested, for some reason the require didn't work.
I ended up adding 'node_modules/bdsmjs/dist/bdsm.js' to webpack entry point by gulp only in development.
Not the most elegant solution, but it works.
Thanks for the help.

**Comment by galtalmor** [comment]
In any case, it might be a good idea to add this to the readme.
I suppose others will encounter this too.

**Comment by morsdyce** [comment]
Documentation and example projects will be coming soon that will show how to use BDSM in various situations.

Thanks for the feedback!

**Comment by galtalmor** [comment]
:+1:
