### ISSUE TITLE
Support for use without `import 'bdsm'`

### ISSUE THREAD

**Issue by sagivf** [500tech/bdsm#151]
Not all projects support ES6. Anyway to get it to work without `import 'bdsm'`
by using a script tag?

**Comment by morsdyce** [comment]
You can use BDSM by including it using a script tag after installing it from npm
`<script src="../node_modules/bdsm/dist/bdsm.js"></script>`

Or you can use unpkg which serves npm packages over CDN
`<script src="https://unpkg.com/bdsm@latest/dist/bdsm.js"></script>`
